### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by jfrader** [manueljlz/gcphone#184]
This repo should not exist without the proper UNMINIFIED version of the source code.
You are infringing it's original license.

**Comment by DmACKGL** [comment]
Hey @jfrader !

From what I see in the commits, someone merged a pull-request which removes all the source code (Check https://github.com/manueljlz/gcphone/commit/c7e78de16ce4b6013346897f63e0f5c2c0bffac1). Everything from https://github.com/manueljlz/gcphone/commit/2a17c3e3bf2813d22558cfcc0a8ada8632c80f35 and back stills there.

I'm no longer the maintainer of this repo but I created a fork where I would add more features and use CGP (Code Good Practices), you can check it out here: https://github.com/DmACKGL/GCPhone-Rewrite

**Comment by jfrader** [comment]
@DmACKGL 
Wow that's bad to hear! Im sorry this happened.
Maybe this repo should be closed then? What would be the best approach to handle this as you don't want to mantain this any longer?

About your new repo that's awesome! I am also working in a React based phone right now. You should take a look at https://github.com/project-error/new-phone-who-dis

**Comment by DmACKGL** [comment]
Hey!

Good to hear, about your project, good luck with it :D

Meanwhile, regarding the repository, I don't have that type of access.

**Comment by manueljlz** [comment]
Fixed issue with source code, thanks for opening this topic. In these months I will go back to give you cane.

**Comment by DmACKGL** [comment]
I can confirm the issue is not fixed, just the HTML source code is published, not the Client/Server code

**Comment by DmACKGL** [comment]
Actually, you just erased all the commits! Revert back to https://github.com/manueljlz/gcphone/commit/2a17c3e3bf2813d22558cfcc0a8ada8632c80f35 ASAP!
